use role {{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DATA_SCIENTIST;
CREATE OR REPLACE NOTEBOOK {{ env.DATAOPS_DATABASE }}.HOP.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_EXERCISE
FROM '@{{ env.DATAOPS_DATABASE }}.HOP.RAG'
MAIN_FILE = 'SKO_RAG_HOP_EXERCISE.ipynb'
QUERY_WAREHOUSE = '{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DS_WH';

ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.hop.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_EXERCISE ADD LIVE VERSION FROM LAST;

use role {{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DATA_SCIENTIST;
CREATE OR REPLACE NOTEBOOK {{ env.DATAOPS_DATABASE }}.HOP.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_SOLUTION
FROM '@{{ env.DATAOPS_DATABASE }}.HOP.RAG'
MAIN_FILE = 'SKO_RAG_HOP_SOLUTION.ipynb'
QUERY_WAREHOUSE = '{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DS_WH';

ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.hop.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_SOLUTION ADD LIVE VERSION FROM LAST;
